name: Traceroute and Ping
on:
  workflow_dispatch:

jobs:
  traceroute_ping:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ping
        env:
         INI: ${{ secrets.SECRET_BARU }}
        run: traceroute ${ INI }
