name: Traceroute and Ping
on:
  workflow_dispatch:

jobs:
  traceroute_ping:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: curl1
        run: curl ifconfig.me

      - name: traceroute1
        run: traceroute 103.6.117.62
        
      - name: ping
        run: ping -c 300 103.6.117.62
        
      - name: traceroute
        run: traceroute 103.6.117.62

      - name: curl
        run: curl ifconfig.me
