name: Traceroute and Ping
on:
  workflow_dispatch:

jobs:
  traceroute_ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install traceroute and ping
        run: sudo apt-get update && sudo apt-get install -y traceroute iputils-ping

      - name: Run traceroute
        run: traceroute google.com

      - name: Run ping
        run: ping -4 -n 5 google.com

      - name: check ip public
        run: curl ifconfig.me
