name: Traceroute and Ping
on:
  workflow_dispatch:

jobs:
  traceroute_ping:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ping
        run: traceroute 103.6.117.2

      - name: curl
        run: curl ifconfig.me
