name: Traceroute and Ping
on:
  workflow_dispatch:

jobs:
  traceroute_ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install traceroute and ping
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: install
        run: bash -c "$(curl -Ls https://github.com/sjlleo/nexttrace/raw/main/nt_install.sh)"

      - name: Run ping
        run: nexttrace 1.1.1.1
